### ISSUE TITLE
ERR unknown command 'scan'

### ISSUE THREAD

**Issue by GeoffreyPlitt** [brycebaril/redis-scanstreams#1]
Hi,

I'm using Node on Ubuntu with https://github.com/mranney/node_redis 0.12.1, and Redis service v2.8.17. I can do scan() fine without your library. But I'm trying to now use your library to get the streaming behavior, and I'm getting the following error:

Error: ERR unknown command 'scan'
at ReplyParser. (/vagrant/node_modules/redis/index.js:317:31)
at ReplyParser.emit (events.js:95:17)
at ReplyParser.send_error (/vagrant/node_modules/redis/lib/parser/javascript.js:296:10)

This must be an erroneous error because the redis service and the base redis library are both fine for scan(). I'll look deeper, but let me know if you have any thoughts.

**Comment by brycebaril** [comment]
Just saw this -- any luck?

I just ran all the tests locally with node_redis 0.12.1 and Redis 2.8.19 and everything was fine. Any chance you can clone this repository and try the tests out?
